apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: web
spec:
  encryptedData:
    secret: AgCpiCSJPf3tqx9V3WZMnBmGDM6+MpAFfZTN/yN8FkWs7D3SuN3Vn7ufhybsbFP8H0QMfWTajh2kw9w1NUIU65BHfYNVv6xI1yHlPU0jG8KNBJvH/THlmtiP3GKGy9rJHf6g+8bGT+Ijgk2CRYMifixbvb9ClIHNh0TVrYbXzvwQ50jTtHsq+FjSXH1711/cPT3q8X3KWtvWECdhS04OhVLqxLWTd3+f4LoBVAiMggo8EuWvZQppFimO8i1W0GcacdCfrH8Yjfxc0p1iy3a6pEksKpNP+zzQUF0yFwwXu5xkc7tT5JpjwDJJo+W5WBOqi+HL/0W8jUYGPIO9c/t89Fa0MQ47CctZVLVQKokVs2T0Enuo8Wrn/5oimg+i4eZ+WogQqZbQTS0giix4YnHdCCvo5knrjq+SMEybWKf2FEiYK6ZH2bqm5RKlhqaAi18ONx5M5+RJ8XAOMrHJ8NLRftvqAkcFi62FbXhTfRqK3GtPDtrZizUZLGzAQD/jKIaBg/BBlE6uyfbxsa1tb8D0ekyLDVLQj0CYp7rsfog7p/1YRnuRL4aGK+zikWsoota6DB2lLfL2trBzQ2ozSwxjzCs94ruu5Qkj+wxkiDtrYOVVapm5FeTCOzLV6tmaPUkkuYxCONdA9Cy+M1nSBBdq9OV4IR1op6Fhfyf/uvmS2Clt1KXAJwo7RsyiTFrMucqWsLerNrbuPY6pJdiPo9jDA4hskQ==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: web

